stages:
  - build
  - test
  - build-wheel
  - push-rc
  - test-rc
  - push-prod

variables:
  TWINE_USERNAME: gitlab-ci-token
  TWINE_PASSWORD: $CI_JOB_TOKEN
  TWINE_REPOSITORY_URL: https://gitlab.lam.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
  IMAGE_BUILD_DIR: $CI_REGISTRY/cpf/docker_builds

# OSX Stages

build-osx:
  stage: build
  tags:
    - osx
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j 2
  cache:
    key: osx
    policy: push
    untracked: true

test-osx:
  stage: test
  tags:
    - osx
  allow_failure: true
  script:
    - cd build
    - make install
    - make test
  cache:
    key: osx
    policy: pull
    untracked: true

wheel36-osx:
  stage: build-wheel
  tags:
    - osx
  script:
    - source /Users/grunner/venv/amazed36/bin/activate
    - python setup.py bdist_wheel
    - delocate-wheel -w wheel/ dist/pylibamazed-*-cp36-*.whl
    - pip install wheel/pylibamazed-*-cp36-*.whl
    - cd /
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /Users/grunner/venv/amazed36/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: osx
    policy: pull
    untracked: true

wheel37-osx:
  stage: build-wheel
  tags:
    - osx
  script:
    - source /Users/grunner/venv/amazed37/bin/activate
    - python setup.py bdist_wheel
    - delocate-wheel -w wheel/ dist/pylibamazed-*-cp37-*.whl
    - pip install wheel/pylibamazed-*-cp37-*.whl
    - cd /
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /Users/grunner/venv/amazed37/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: osx
    policy: pull
    untracked: true

wheel38-osx:
  stage: build-wheel
  tags:
    - osx
  script:
    - source /Users/grunner/venv/amazed38/bin/activate
    - python setup.py bdist_wheel
    - delocate-wheel -w wheel/ dist/pylibamazed-*-cp38-*.whl
    - pip install wheel/pylibamazed-*-cp38-*.whl
    - cd /
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /Users/grunner/venv/amazed38/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: osx
    policy: pull
    untracked: true
  
push-rc-36-osx:
  stage: push-rc
  tags:
    - osx
  when: manual
  before_script:
    - source /Users/grunner/venv/amazed36/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --skip-existing --disable-progress-bar wheel/pylibamazed-*-cp36-*.whl
  cache:
    key: osx
    policy: pull
    untracked: true
  dependencies:
    - wheel36-osx

push-rc-37-osx:
  stage: push-rc
  tags:
    - osx
  when: manual
  before_script:
    - source /Users/grunner/venv/amazed37/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --skip-existing --disable-progress-bar wheel/pylibamazed-*-cp37-*.whl
  cache:
    key: osx
    policy: pull
    untracked: true
  dependencies:
    - wheel37-osx

push-rc-38-osx:
  stage: push-rc
  tags:
    - osx
  when: manual
  before_script:
    - source /Users/grunner/venv/amazed38/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --skip-existing --disable-progress-bar wheel/pylibamazed-*-cp38-*.whl
  cache:
    key: osx
    policy: pull
    untracked: true
  dependencies:
    - wheel38-osx

# Manylinux stages

.build-manylinux:
  stage: build
  script:
    - source /venv/p36/bin/activate
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j4
  cache:
    policy: push
    untracked: true

.test-manylinux:
  stage: test
  allow_failure: true
  script:
    - cd build
    - make install
    - make test
  cache:
    policy: pull
    untracked: true

.wheel-manylinux:
  stage: build-wheel
  before_script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
  script:
    - source /venv/p$PYTHON_VERSION/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp$PYTHON_VERSION-*.whl -w wheel --plat $PLATFORM
    - pip install wheel/pylibamazed-*-cp$PYTHON_VERSION-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p$PYTHON_VERSION/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    policy: pull
    untracked: true

.push-rc-manylinux:
  stage: push-rc
  script:
    - source /venv/p$PYTHON_VERSION/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp$PYTHON_VERSION-*.whl
  cache:
    policy: pull
    untracked: true

# Manylinux1 stages

build-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  extends: .build-manylinux
  when: manual
  cache:
    key: manylinux1

test-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  extends: .test-manylinux
  when: manual
  cache:
    key: manylinux1

wheel36-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  variables:
    PYTHON_VERSION: "36"
    PLATFORM: "manylinux1_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux1

wheel37-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  variables:
    PYTHON_VERSION: "37"
    PLATFORM: "manylinux1_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux1

wheel38-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  variables:
    PYTHON_VERSION: "38"
    PLATFORM: "manylinux1_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux1

push-rc-36-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  variables:
    PYTHON_VERSION: "36"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux1
  dependencies:
    - wheel36-manylinux1

push-rc-37-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  variables:
    PYTHON_VERSION: "37"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux1
  dependencies:
    - wheel37-manylinux1

push-rc-38-manylinux1:
  image: $IMAGE_BUILD_DIR/amazed-manylinux1
  variables:
    PYTHON_VERSION: "38"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux1
  dependencies:
    - wheel38-manylinux1

# Manylinux2010 stages

build-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  extends: .build-manylinux
  when: manual
  cache:
    key: manylinux2010

test-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  extends: .test-manylinux
  when: manual
  cache:
    key: manylinux2010

wheel36-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  variables:
    PYTHON_VERSION: "36"
    PLATFORM: "manylinux2010_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux2010

wheel37-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  variables:
    PYTHON_VERSION: "37"
    PLATFORM: "manylinux2010_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux2010

wheel38-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  variables:
    PYTHON_VERSION: "38"
    PLATFORM: "manylinux2010_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux2010

push-rc-36-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  variables:
    PYTHON_VERSION: "36"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux2010
  dependencies:
    - wheel36-manylinux2010

push-rc-37-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  variables:
    PYTHON_VERSION: "37"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux2010
  dependencies:
    - wheel37-manylinux2010

push-rc-38-manylinux2010:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2010
  variables:
    PYTHON_VERSION: "38"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux2010
  dependencies:
    - wheel38-manylinux2010

# Manylinux2014 stages

build-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  extends: .build-manylinux
  when: manual
  cache:
    key: manylinux2014

test-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  extends: .test-manylinux
  when: manual
  cache:
    key: manylinux2014

wheel36-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  variables:
    PYTHON_VERSION: "36"
    PLATFORM: "manylinux2014_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux2014

wheel37-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  variables:
    PYTHON_VERSION: "37"
    PLATFORM: "manylinux2014_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux2014

wheel38-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  variables:
    PYTHON_VERSION: "38"
    PLATFORM: "manylinux2014_x86_64"
  extends: .wheel-manylinux
  when: manual
  cache:
    key: manylinux2014

push-rc-36-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  variables:
    PYTHON_VERSION: "36"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux2014
  dependencies:
    - wheel36-manylinux2014

push-rc-37-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  variables:
    PYTHON_VERSION: "37"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux2014
  dependencies:
    - wheel37-manylinux2014

push-rc-38-manylinux2014:
  image: $IMAGE_BUILD_DIR/amazed-manylinux2014
  variables:
    PYTHON_VERSION: "38"
  extends: .push-rc-manylinux
  when: manual
  cache:
    key: manylinux2014
  dependencies:
    - wheel38-manylinux2014
