stages:
  - build
  - test
  - build-wheel
  - push-rc
  - test-rc
  - push-prod

variables:
  TWINE_USERNAME: gitlab-ci-token
  TWINE_PASSWORD: $CI_JOB_TOKEN
  TWINE_REPOSITORY_URL: https://gitlab.lam.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi

# OSX Stages

build-osx:
  stage: build
  tags:
    - osx
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j 2
  cache:
    key: osx
    policy: push
    untracked: true

test-osx:
  stage: test
  tags:
    - osx
  allow_failure: true
  script:
    - cd build
    - make install
    - make test
  cache:
    key: osx
    policy: pull
    untracked: true

wheel36-osx:
  stage: build-wheel
  tags:
    - osx
  script:
    - source /Users/grunner/venv/amazed36/bin/activate
    - python setup.py bdist_wheel
    - delocate-wheel -w wheel/ dist/pylibamazed-*-cp36-cp36m-*.whl
    - pip install wheel/pylibamazed-*-cp36-cp36m-*.whl
    - cd /
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /Users/grunner/venv/amazed36/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: osx
    policy: pull
    untracked: true

wheel37-osx:
  stage: build-wheel
  tags:
    - osx
  when: manual
  script:
    - source /Users/grunner/venv/amazed37/bin/activate
    - python setup.py bdist_wheel
    - delocate-wheel -w wheel/ dist/pylibamazed-*-cp37-cp37m-*.whl
    - pip install wheel/pylibamazed-*-cp37-cp37m-*.whl
    - cd /
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /Users/grunner/venv/amazed37/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: osx
    policy: pull
    untracked: true

wheel38-osx:
  stage: build-wheel
  tags:
    - osx
  when: manual
  script:
    - source /Users/grunner/venv/amazed38/bin/activate
    - python setup.py bdist_wheel
    - delocate-wheel -w wheel/ dist/pylibamazed-*-cp38-cp38-*.whl
    - pip install wheel/pylibamazed-*-cp38-cp38-*.whl
    - cd /
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /Users/grunner/venv/amazed38/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: osx
    policy: pull
    untracked: true
  
push-rc-36-osx:
  stage: push-rc
  tags:
    - osx
  when: manual
  before_script:
    - source /Users/grunner/venv/amazed36/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --skip-existing --disable-progress-bar wheel/pylibamazed-*-cp36-cp36m-*.whl
  cache:
    key: osx
    policy: pull
    untracked: true
  dependencies:
    - wheel36-osx

push-rc-37-osx:
  stage: push-rc
  tags:
    - osx
  when: manual
  before_script:
    - source /Users/grunner/venv/amazed37/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --skip-existing --disable-progress-bar wheel/pylibamazed-*-cp37-cp37m-*.whl
  cache:
    key: osx
    policy: pull
    untracked: true
  dependencies:
    - wheel37-osx

push-rc-38-osx:
  stage: push-rc
  tags:
    - osx
  when: manual
  before_script:
    - source /Users/grunner/venv/amazed38/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --skip-existing --disable-progress-bar wheel/pylibamazed-*-cp38-cp38-*.whl
  cache:
    key: osx
    policy: pull
    untracked: true
  dependencies:
    - wheel38-osx

# Manylinux2010 stages

build-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: build
  when: manual
  script:
    - source /venv/p36/bin/activate
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j4
  cache:
    key: manylinux2010
    policy: push
    untracked: true

test-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: test
  when: manual
  allow_failure: true
  script:
    - cd build
    - make install
    - make test
  cache:
    key: manylinux2010
    policy: pull
    untracked: true

wheel36-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: build-wheel
  when: manual
  script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
    - source /venv/p36/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp36-cp36m-*.whl -w wheel --plat manylinux2010_x86_64
    - pip install wheel/pylibamazed-*-cp36-cp36m-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p36/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: manylinux2010
    policy: pull
    untracked: true

wheel37-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: build-wheel
  when: manual
  script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
    - source /venv/p37/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp37-cp37m-*.whl -w wheel --plat manylinux2010_x86_64
    - pip install wheel/pylibamazed-*-cp37-cp37m-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p37/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: manylinux2010
    policy: pull
    untracked: true

wheel38-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: build-wheel
  when: manual
  script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
    - source /venv/p38/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp38-cp38-*.whl -w wheel --plat manylinux2010_x86_64
    - pip install wheel/pylibamazed-*-cp38-cp38-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p38/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: manylinux2010
    policy: pull
    untracked: true

push-rc-36-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: push-rc
  when: manual
  script:
    - source /venv/p36/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp36-cp36m-*.whl
  cache:
    key: manylinux2010
    policy: pull
    untracked: true
  dependencies:
    - wheel36-manylinux2010

push-rc-37-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: push-rc
  when: manual
  script:
    - source /venv/p37/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp37-cp37m-*.whl
  cache:
    key: manylinux2010
    policy: pull
    untracked: true
  dependencies:
    - wheel37-manylinux2010

push-rc-38-manylinux2010:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2010
  stage: push-rc
  when: manual
  script:
    - source /venv/p38/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp38-cp38-*.whl
  cache:
    key: manylinux2010
    policy: pull
    untracked: true
  dependencies:
    - wheel38-manylinux2010

# Manylinux2014 stages

build-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: build
  script:
    - source /venv/p36/bin/activate
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j4
  cache:
    key: manylinux2014
    policy: push
    untracked: true

test-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: test
  allow_failure: true
  script:
    - cd build
    - make install
    - make test
  cache:
    key: manylinux2014
    policy: pull
    untracked: true

wheel36-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: build-wheel
  script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
    - source /venv/p36/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp36-cp36m-*.whl -w wheel --plat manylinux2014_x86_64
    - pip install wheel/pylibamazed-*-cp36-cp36m-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p36/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: manylinux2014
    policy: pull
    untracked: true

wheel37-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: build-wheel
  script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
    - source /venv/p37/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp37-cp37m-*.whl -w wheel --plat manylinux2014_x86_64
    - pip install wheel/pylibamazed-*-cp37-cp37m-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p37/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: manylinux2014
    policy: pull
    untracked: true

wheel38-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: build-wheel
  script:
    - cd build
    - make install
    - make clean_python_build
    - cd ..
    - source /venv/p38/bin/activate
    - python setup.py bdist_wheel
    - auditwheel repair dist/pylibamazed-*-cp38-cp38-*.whl -w wheel --plat manylinux2014_x86_64
    - pip install wheel/pylibamazed-*-cp38-cp38-*.whl
    - python -c "import pylibamazed; import pkg_resources; print(pkg_resources.get_distribution('pylibamazed').version)"
    - cd /
    - python -c "from pylibamazed.redshift import get_version ; print(get_version())"
  after_script:
    - source /venv/p38/bin/activate
    - pip uninstall -y pylibamazed
  artifacts:
    paths:
      - wheel/
    expire_in: 1 week
  cache:
    key: manylinux2014
    policy: pull
    untracked: true

push-rc-36-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: push-rc
  when: manual
  script:
    - source /venv/p36/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp36-cp36m-*.whl
  cache:
    key: manylinux2014
    policy: pull
    untracked: true
  dependencies:
    - wheel36-manylinux2014

push-rc-37-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: push-rc
  when: manual
  script:
    - source /venv/p37/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp37-cp37m-*.whl
  cache:
    key: manylinux2014
    policy: pull
    untracked: true
  dependencies:
    - wheel37-manylinux2014

push-rc-38-manylinux2014:
  image: gitlab.lam.fr:5050/cpf/docker_builds/amazed-manylinux2014
  stage: push-rc
  when: manual
  script:
    - source /venv/p38/bin/activate
    - twine upload --repository-url $TWINE_REPOSITORY_URL --verbose --disable-progress-bar wheel/pylibamazed-*-cp38-cp38-*.whl
  cache:
    key: manylinux2014
    policy: pull
    untracked: true
  dependencies:
    - wheel38-manylinux2014
