# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # C++ hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.1'
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ['-style=LLVM', '-i']

  # Yaml and JSON hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        types: [yaml]
      - id: pretty-format-json
        types: [json]
        args: ['--autofix', '--no-sort-keys']

  # Python hooks
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        files: 'pylibamazed'
        exclude: 'redshift.py'
        types: [python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        files: 'pylibamazed'
        exclude: 'redshift.py'
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: 'pylibamazed'
        exclude: 'redshift.py'
        types: [python]
