# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # C++ hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v13.0.1"
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ["-style=LLVM", "-i"]

  # Yaml and JSON hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        types: [yaml]
      - id: pretty-format-json
        types: [json]
        args: ["--autofix", "--no-sort-keys"]

  # Python hooks
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        files: "pylibamazed"
        exclude: "redshift.py"
        types: [python]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: "pylibamazed"
        exclude: "redshift.py"
        language_version: python3.9
        args: ["--line-length=110"]
        types: [python]
