file(READ ${PROJECT_SOURCE_DIR}/VERSION VERSION_UNSTRP)
string(STRIP ${VERSION_UNSTRP} VERSION)
find_package(Git)
if(GIT_FOUND)
  execute_process(COMMAND ${GIT_EXECUTABLE} describe --match="" --dirty --always OUTPUT_VARIABLE GIT_REVISION OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT GIT_REVISION)
    set(GIT_REVISION VERSION)
  else()
    string(REGEX MATCH "dirty" DIRTY_TAG ${GIT_REVISION})
    if(DIRTY_TAG)
      message(STATUS "Uncommited changes detected. Using -dirty flag.")
    endif()
  endif()
else()
  set(GIT_REVISION VERSION)
endif()
