file(READ ${PROJECT_SOURCE_DIR}/VERSION VERSION_UNSTRP)
string(STRIP ${VERSION_UNSTRP} VERSION)
set(GIT_REVISION ${VERSION})
find_package(Git)
if(GIT_FOUND)
  execute_process(COMMAND ${GIT_EXECUTABLE} describe --match="" --dirty --always OUTPUT_VARIABLE REVISION OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(REVISION)
    set(GIT_REVISION "${GIT_REVISION}+git${REVISION}")
    string(REGEX MATCH "dirty" DIRTY_TAG ${REVISION})
    if(DIRTY_TAG)
      string(REPLACE "-" "." GIT_REVISION ${GIT_REVISION})
      message(STATUS "Uncommited changes detected. Using -dirty flag.")
    endif()
  endif()
endif()
